baseURL = "https://www.smhtpz.com/"
languageCode = "en-us"
title = "Semih Topuz"
theme = "PaperMod"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1


[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = 20

[params]
    defaultTheme = "dark" 
    ShowShareButtons = false
    
    [params.logo]
        light = "images/logo-light.png"
        dark = "images/logo-dark.png"
        alt = "Semih Topuz - Akademik Web Sitesi"

    [params.profileMode]
        enabled = true
        title = "Semih Topuz"
        subtitle = "PhD Candidate in Educational Measurement and Evaluation | Researcher focusing on AI, Psychometrics, and Data-Driven Assessment"
        
        [[params.profileMode.buttons]]
            name = "Publications"
            url = "/publications"

        [[params.profileMode.buttons]]
            name = "About"
            url = "/about"

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/smhtpz"
[[params.socialIcons]]
    name = "googlescholar"
    url = "https://scholar.google.com/citations?user=MjAhoTkAAAAJ&hl"
[[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/smhtpz"